// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEXC-JsgN3CeKVV5tNWpXnEgW3MfkOmYg',
    appId: '1:174676975944:web:dbec5bd30fab2c51d1d37d',
    messagingSenderId: '174676975944',
    projectId: 'bookmarkapp-15116',
    authDomain: 'bookmarkapp-15116.firebaseapp.com',
    storageBucket: 'bookmarkapp-15116.firebasestorage.app',
    measurementId: 'G-XS4DYVMLNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK5DNGRzeIrqBJvWta15kCHuQiy4eYuic',
    appId: '1:174676975944:android:1acda21627520f38d1d37d',
    messagingSenderId: '174676975944',
    projectId: 'bookmarkapp-15116',
    storageBucket: 'bookmarkapp-15116.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZLg5z09W2jnj3dqt00tEesjrBeEA5HJo',
    appId: '1:174676975944:ios:ad0dd35f84ce4699d1d37d',
    messagingSenderId: '174676975944',
    projectId: 'bookmarkapp-15116',
    storageBucket: 'bookmarkapp-15116.firebasestorage.app',
    iosBundleId: 'com.example.thisuxnew',
  );
}
